# Generated by Django 3.2.8 on 2021-11-11 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_auto_20211111_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='publicado',
            new_name='publicada',
        ),
    ]
